### ISSUE TITLE
End-to-end command -> docker-in-docker run leads to network issues

### ISSUE THREAD

**Issue by lwsanty** [bblfsh/performance#3]
**Environment**
OSX host
```
FROM docker:latest

COPY ./bblfsh-performance /usr/bin/
WORKDIR /usr/bin

ENTRYPOINT ["./bblfsh-performance"]
```

**Command**
```
docker run --privileged \
--rm \
-e LOG_LEVEL=debug \
-e INFLUX_ADDRESS="http://localhost:8086" \
-e INFLUX_USERNAME="" \
-e INFLUX_PASSWORD="" \
-e INFLUX_DB=mydb \
-e INFLUX_MEASUREMENT=benchmark \
-v /var/run/docker.sock:/var/run/docker.sock \
-v ./data/fixtures:/data \
--name bblfsh-performance \
bblfsh-performance end-to-end --language=go --commit=3d9682b --extension=".go" /data
```

**Observed**
docker client cannot dial address because of hostport `localhost:9432`

**Possible solution**
Use another docker client and bind to address in the docker network `172.17...`

**Comment by creachadair** [comment]
Is this issue only on macOS, or does it afflict Linux too? I ask because I've had some success working around this issue on macOS by binding to the wildcard interface instead of `localhost`. As long as the ports are published that should allow the bridge network to reach the container. (You might have already tried that, perhaps)

**Comment by lwsanty** [comment]
@creachadair good point, I'll recheck this case on the Linux machine

**Comment by lwsanty** [comment]
Closing this one because of reasons:
- performance cli will be used in container only inside the CI environment, which is linux by default
- during local debug on the binary this issue is not reproduced
